#installing all the packages
install.packages('tidyverse',dependencies = TRUE)
library(tidyverse)
install.packages('skimr')
library(skimr)
install.packages("ggplot2")
install.packages('tidyselect')

# imported data from environment tab

#display all column names from Dataframes
head(Divvy_Trips_2019_Q2)
colnames(Divvy_Trips_2019_Q2)
colnames(Divvy_Trips_2019_Q3)
colnames(Divvy_Trips_2019_Q4)
colnames(Divvy_Trips_2020_Q1)

str(Divvy_Trips_2019_Q2)
str(Divvy_Trips_2019_Q3)
str(Divvy_Trips_2019_Q4)
str(Divvy_Trips_2020_Q1)

# rename column names of Q2_2019,Q3_2019,Q4_2019 to match with last quarter Q1_2020 data

Q2_2019<- rename(Divvy_Trips_2019_Q2, ride_id = V1
                 ,rideable_type = V4
                 ,started_at = V2
                 ,ended_at = V3  
                 ,start_station_name = V7
                 ,start_station_id = V6
                 ,end_station_name = V9
                 ,end_station_id = V8
                 ,member_casual = V10)
            

str(Q2_2019)    
Q3_2019 <- rename(Divvy_Trips_2019_Q3
                   ,ride_id = trip_id
                   ,rideable_type = bikeid 
                   ,started_at = start_time  
                   ,ended_at = end_time  
                   ,start_station_name = from_station_name 
                   ,start_station_id = from_station_id 
                   ,end_station_name = to_station_name 
                   ,end_station_id = to_station_id 
                   ,member_casual = usertype)
str(Q3_2019)
(Q4_2019 <- rename(Divvy_Trips_2019_Q4
                   ,ride_id = trip_id
                   ,rideable_type = bikeid 
                   ,started_at = start_time  
                   ,ended_at = end_time  
                   ,start_station_name = from_station_name 
                   ,start_station_id = from_station_id 
                   ,end_station_name = to_station_name 
                   ,end_station_id = to_station_id 
                   ,member_casual = usertype))

str(Q4_2019)

colnames(Q2_2019)
colnames(Q3_2019)
colnames(Q4_2019)

str(Q2_2019)
str(Q3_2019)
str(Q4_2019)

# remove top row from Q2_2019

Q2_2019<- subset.data.frame(Q2_2019, ride_id != "01 - Rental Details Rental ID")
head(Q2_2019)

# update data types of the columns in Q2,Q3,Q4 2019

Q4_2019 <-  mutate(Q4_2019, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type)) 
Q3_2019 <-  mutate(Q3_2019, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type)) 
Q2_2019 <-  mutate(Q2_2019, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type))
Q2_2019 <-  mutate(Q2_2019, start_station_id  = as.integer(start_station_id)
                   ,end_station_id  = as.integer(end_station_id))

# checking for the changes

str(Q2_2019)
str(Q3_2019)
str(Q4_2019)
str(Divvy_Trips_2020_Q1)

#combining 4 quarters data in one dataframe

Divvy_trips<- bind_rows(Q2_2019,Q3_2019,Q4_2019,Divvy_Trips_2020_Q1)
head(Divvy_trips)

colnames(Divvy_trips)
# removing the columns longitude and latitude, birth year , gender)
Divvy_trips<- Divvy_trips %>% 
  select(-c(V5,V11,V12,gender,birthyear,start_lat,start_lng,end_lat,end_lng,tripduration))

# check list of columns now available
colnames(Divvy_trips)
nrow(Divvy_trips)
dim(Divvy_trips)
str(Divvy_trips)
summary(Divvy_trips)
#for consistency updating values in member_casual from subscriber=member, customer=casual
Divvy_trips<-Divvy_trips %>% 
  mutate(member_casual=recode(member_casual
                              ,"Subscriber"="member"
                              ,"Customer"="casual"))

table(Divvy_trips$date)
#add date columns so that data can be summarized on day, week or month 
#took date from start_at column

Divvy_trips$date <- as.Date(Divvy_trips$started_at) #The default format is yyyy-mm-dd
Divvy_trips$month <- format(as.Date(Divvy_trips$date), "%m")
Divvy_trips$day <- format(as.Date(Divvy_trips$date), "%d")
Divvy_trips$year <- format(as.Date(Divvy_trips$date), "%Y")
Divvy_trips$day_of_week <- format(as.Date(Divvy_trips$date), "%A")

head(Divvy_trips)

#calculate ride_length in seconds from ended_at-started_at
Divvy_trips$ride_length <- difftime(Divvy_trips$ended_at,Divvy_trips$started_at)
#
head(Divvy_trips)


str(Divvy_trips)
# check type of the ride_length column
is.factor(Divvy_trips$ride_length)
is.numeric(Divvy_trips$ride_length)
is.character(Divvy_trips$ride_length)
#converting the ride_length in to numeric
Divvy_trips$ride_length<- as.numeric(as.character(Divvy_trips$ride_length))
#checking the type
is.numeric(Divvy_trips$ride_length)
#removing the rows which has HQ QR as start station or ride_length< 0 (maintenance checkout)
Divvy_trips_1<- Divvy_trips[!(Divvy_trips$start_station_name=="HQ QR"|Divvy_trips$ride_length<0),]
head(Divvy_trips_1)
nrow(Divvy_trips)
nrow(Divvy_trips_1)

mean(Divvy_trips_1$ride_length)
median(Divvy_trips_1$ride_length)
min(Divvy_trips_1$ride_length)
max(Divvy_trips_1$ride_length)

#aggregate() ride_length on members/casuals
aggregate(Divvy_trips_1$ride_length ~ Divvy_trips_1$member_casual, FUN = mean)
aggregate(Divvy_trips_1$ride_length ~ Divvy_trips_1$member_casual, FUN = median)
aggregate(Divvy_trips_1$ride_length ~ Divvy_trips_1$member_casual, FUN = min)
aggregate(Divvy_trips_1$ride_length ~ Divvy_trips_1$member_casual, FUN = max)
#aggregate data on members/casuals and day of the week
aggregate(Divvy_trips_1$ride_length ~ Divvy_trips_1$member_casual+Divvy_trips_1$day_of_week,FUN = mean)

Divvy_trips_1$day_of_week<-ordered(Divvy_trips_1$day_of_week,levels=c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))

Divvy_trips_1_org1<-Divvy_trips_1 %>% mutate(weekday = wday(started_at,label = TRUE)) %>% 
  group_by(member_casual,weekday) %>% 
  summarise(numberofrides=n(),average_duration=mean(ride_length)) %>% 
  arrange(member_casual,weekday)
Divvy_trips_1_org1

#visualize
Divvy_trips_1_org1 %>% ggplot(aes(x=weekday,y=numberofrides,fill=member_casual))+geom_col(position = "dodge")

Divvy_trips_1_org1 %>% ggplot(aes(x=weekday,y=average_duration,fill=member_casual))+geom_col(position="dodge" )

write_csv(Divvy_trips_1,file="./Divvy_trips_1.csv")


  
